Add : devuan , chimera , wolfi linux support to otter-init

diff --git a/internal/insidecontainer/assets/otter-init b/internal/insidecontainer/assets/otter-init
--- a/internal/insidecontainer/assets/otter-init
+++ b/internal/insidecontainer/assets/otter-init
@@ -481,6 +481,33 @@ if [ "${shell_pkg}" = "ash" ]; then
 	shell_pkg="bash"
 fi
 
+# get_distro_id will read the ID field from /etc/os-release, falling back to
+# /usr/lib/os-release, and print it. Exits with an error if neither file
+# exists.
+# Arguments:
+#   None
+# Expected global variables:
+#   None
+# Expected env variables:
+#   None
+# Outputs:
+#   The distro ID (e.g. alpine, wolfi, chimera, ubuntu, debian, devuan)
+get_distro_id()
+{
+	if [ -e /etc/os-release ]; then
+		# shellcheck disable=SC1091
+		. /etc/os-release
+	elif [ -e /usr/lib/os-release ]; then
+		# shellcheck disable=SC1091
+		. /usr/lib/os-release
+	else
+		printf "Error: could not find /etc/os-release or /usr/lib/os-release.\n" >&2
+		printf "Error: could not determine the distro of this container.\n" >&2
+		exit 127
+	fi
+	printf "%s" "${ID}"
+}
+
 # setup_pkg_manager_hooks will create umount/remount hooks script for a package
 # manager. Mainly used by apt and pacman.
 # Arguments:
@@ -715,43 +742,94 @@ setup_apk()
 			shell_pkg="bash"
 		fi
 	fi
-	deps="
+	distro_id="$(get_distro_id)"
+	case "${distro_id}" in
+		alpine)
+			apk add alpine-base
+			deps="
+				coreutils
+				docs
+				gcompat
+				libc-utils
+				lsof
+				man-pages
+				mandoc
+				musl-utils
+				openssh-client-default
+				pinentry
+				tar
+				vte3
+				$(apk search -q mesa-dri)
+				$(apk search -q mesa-vulkan)
+			"
+			;;
+		wolfi)
+			apk add wolfi-base
+			deps="
+				coreutils
+				busybox
+				gnutar
+				man-db
+				mesa
+				openssh-client
+				pinentry
+				posix-libc-utils
+				script
+			"
+			;;
+		chimera)
+			apk add base-bootstrap
+			apk upgrade -Ua
+			apk add chimera-repo-user
+			apk update
+			deps="
+				base-full-man
+				bc-gh
+				gtar
+				libarchive-progs
+				libcap-progs
+				lsof
+				mesa-dri
+				ncurses-term
+				opendoas
+				openssh
+				util-linux-mount
+				vte
+				wget2
+			"
+			;;
+		*)
+			printf "Error: unsupported apk-based distro '%s'.\n" "${distro_id}"
+			printf "Error: could not set up base dependencies.\n"
+			exit 127
+			;;
+	esac
+	deps="${deps}
 		${shell_pkg}
 		bash
 		bash-completion
 		bc
 		bzip2
-		coreutils
 		curl
 		diffutils
-		docs
 		findmnt
 		findutils
-		gcompat
 		gnupg
 		gpg
 		iproute2
 		iputils
 		keyutils
 		less
-		libc-utils
 		libcap
-		lsof
-		man-pages
-		mandoc
 		mount
-		musl-utils
 		ncurses
 		ncurses-terminfo
 		net-tools
-		openssh-client-default
 		pigz
-		pinentry
 		python3
 		rsync
 		shadow
 		sudo
-		tar
 		tcpdump
 		tree
 		tzdata
@@ -760,15 +838,12 @@ setup_apk()
 		util-linux
 		util-linux-login
 		util-linux-misc
-		vte3
 		vulkan-loader
 		wget
 		which
 		xauth
 		xz
 		zip
-		$(apk search -q mesa-dri)
-		$(apk search -q mesa-vulkan)
 		$(apk search -qe procps)
 	"
 	# shellcheck disable=SC2086
@@ -834,7 +909,30 @@ setup_apt()
 			shell_pkg="bash"
 		fi
 	fi
-	deps="
+	distro_id="$(get_distro_id)"
+	case "${distro_id}" in
+		ubuntu)
+			distro_deps="
+				systemd
+			"
+			;;
+		debian)
+			distro_deps="
+				systemd
+			"
+			;;
+		devuan)
+			distro_deps="
+				sysvinit
+			"
+			;;
+		*)
+			printf "Error: unsupported apt-based distro '%s'.\n" "${distro_id}"
+			printf "Error: could not set up base dependencies.\n"
+			exit 127
+			;;
+	esac
+	deps="${distro_deps}
 		${shell_pkg}
 		apt-utils
 		bash-completion
